In [1]:
import numpy as np

In [21]:
A_not_norm1 = np.array([[1,1,1], [2,1,1], [2,2,2]])
A = np.array([[i+j + (np.random.randint(0,100)-50)/100 for i in range(3)] for j in range(0,3)])
A

array([[-0.08,  1.41,  2.32],
       [ 1.46,  1.75,  3.24],
       [ 1.9 ,  2.96,  4.04]])

In [22]:
B = np.array([np.random.randint(0,100)/10 for _ in range(3)])
B

array([1.2, 1.2, 5.3])

In [28]:
x = np.linalg.inv(A) @ B
x

array([ 0.37365831,  4.85150993, -2.41842083])

In [29]:
x1 = np.linalg.pinv(A) @ B
x1
print(x1)
A @ x1 - B

[ 0.37365831  4.85150993 -2.41842083]


array([-6.43929354e-15, -3.77475828e-15, -8.88178420e-15])

In [30]:
x2 = np.linalg.inv(A_not_norm1) @ B
x2

LinAlgError: Singular matrix

In [31]:
x3 = np.linalg.pinv(A_not_norm1) @ B
print(x3)
A_not_norm1 @ x3 - B


[-1.16  1.76  1.76]


array([ 1.16000000e+00,  1.11022302e-15, -5.80000000e-01])