In [29]:
import numpy as np

In [30]:

def matrix_from_keyboard(m,n, A =[]):
    
    for i in range(m):
        while True:
            row = input(f"enter row {i+1} of A ")
            row_list = [float(x) for x in row.split()]
            if len(row_list) == n:
                A.append(row_list)
                break
            else:
                print(f"must be {n} ")
    return np.array(A)

In [31]:
A_rows = int(input("rows of A: "))
A_cols = int(input("columns of A: "))
A = []
matrix_from_keyboard(A_rows, A_cols, A)

while True:
    b_input = input(f"Enter b ")
    B = np.array([float(x) for x in b_input.split()])
    if len(B) == A_rows:
        break
    else:
        print(f"must be {A_rows} ")


rows of A: 3
columns of A: 4
enter row 1 of A 2 1 1 3
enter row 2 of A 1 0 1 -1
enter row 3 of A 1 1 0 4
Enter b 3 5 6


In [32]:
print(A)
B

[[2.0, 1.0, 1.0, 3.0], [1.0, 0.0, 1.0, -1.0], [1.0, 1.0, 0.0, 4.0]]


array([3., 5., 6.])

In [37]:
v = np.array(np.random.randint(0,10,A_cols))
v

array([2, 0, 5, 3])

In [35]:
A_pinv = np.linalg.pinv(A)
x1 = A_pinv @ B
x1
print(A_pinv, x1, sep= "\n")
A @ x1 - B

[[ 0.2         0.26666667 -0.06666667]
 [ 0.04444444  0.02222222  0.02222222]
 [ 0.15555556  0.24444444 -0.08888889]
 [ 0.02222222 -0.15555556  0.17777778]]
[1.53333333 0.37777778 1.15555556 0.35555556]


array([ 2.66666667, -2.66666667, -2.66666667])

In [38]:
A_pinv@ B +v - A_pinv @ A @ v 

array([-0.2       , -0.82222222,  3.62222222,  1.08888889])