In [1]:
import scipy as sp
import numpy as np
import sympy as smp

In [22]:
import math
def create_function(expression):
    t = smp.symbols('t')
    func = smp.lambdify(t, expression, 'numpy')
    return func



In [28]:

while True:
    try:
        rows =  int(input("ROWS: "))
        break
    except Exception:
        print("SHOULD BE INT ")
while True:
    try:        
        columns =int(input("COLUMNS: "))
        break
    except Exception:
        print("SHOULD BE INT ")

A_key = np.zeros((rows, columns))

ROWS a
SHOULD BE INT 
ROWS A
SHOULD BE INT 
ROWS A
SHOULD BE INT 
ROWS a
SHOULD BE INT 
ROWS a
SHOULD BE INT 
ROWS a
SHOULD BE INT 
ROWS a
SHOULD BE INT 
ROWS 2
COLUMNS 2


In [29]:
A_key


array([[0., 0.],
       [0., 0.]])

In [19]:
A = lambda t:np.array([[t*50-1.23, np.sin(t)+2], [(t*2)**2 + np.pi, np.cos(t)], [np.exp(t), np.cos(t)**2]])
b = np.array([1.4, -2.12, 3])
v = lambda t: np.array([t*5-3, np.log(t)]) 

In [20]:
T =3

In [21]:
A(0)[0]

array([-1.23,  2.  ])

In [191]:
from scipy.integrate import quad_vec

P = quad_vec(lambda tau: A(tau) @ A(tau).T, 0, T )[0]

In [192]:

x_hat= lambda tau: A(tau).T @ np.linalg.pinv(P) @ b
x_hat(3)#1.45

array([1.28405566, 0.37183584])

In [193]:
Av = quad_vec(lambda tau: A(tau) @ v(tau).T, 0, T )[0]


In [194]:
Omega_xt =  lambda t : A(t).T @ np.linalg.pinv(P) @b + v(t) - A(t).T @ np.linalg.pinv(P) @ Av # 1.43

In [195]:
Omega_xt(3) 

array([1.45955472, 0.17133515])

In [196]:
eps_sq = b.T @ b - b.T @ P @ np.linalg.pinv(P) @ b
eps_sq

2.327027459614328e-13

In [197]:
check1 = quad_vec(lambda tau: A(tau) @ Omega_xt(tau),0, 3)[0]
check1

array([ 1.4 , -2.12,  3.  ])

In [198]:
check2 = quad_vec(lambda tau: A(tau) @ x_hat(tau),0, 3)[0]
check2

array([ 1.4 , -2.12,  3.  ])

In [199]:
matrices_A_t = []
matrices_A_j = []
N = 4
length = np.array((A(1).T @ A(1))).shape[0]
def check(N):
    answ = np.zeros((length * (N ), length * (N )))
    # Compute matrices_A_t and matrices_A_j
    for i in range(N ):
        A_ti = A(T/(N-1) * i).T
        A_tj = A(T/(N-1) * i)
        matrices_A_t.append(np.array(A_ti))
        matrices_A_j.append(np.array(A_tj))
    for i in range(N ):
        for j in range(N):
            answ[i*length:(i+1)*length, j*length:(j+1)*length] = np.dot(matrices_A_t[i], matrices_A_j[j])
    determinant = np.linalg.det(answ)

    print("Determinant:", determinant)

    print(answ)
for i in range(2,N+1):
    check(i)

Determinant: 4.2151029686080705e-10
[[ 1.23825044e+01  1.68159265e+00 -1.45963375e+02 -4.76364562e+00]
 [ 1.68159265e+00  6.00000000e+00  3.23017130e+02  4.27233266e+00]
 [-1.45963375e+02  3.23017130e+02  2.25650110e+04  3.32882324e+02]
 [-4.76364562e+00  4.27233266e+00  3.32882324e+02  6.52504692e+00]]
Determinant: 0.0
[[ 1.23825044e+01  1.68159265e+00 -1.45963375e+02 -4.76364562e+00
   1.23825044e+01  1.68159265e+00]
 [ 1.68159265e+00  6.00000000e+00  3.23017130e+02  4.27233266e+00
   1.68159265e+00  6.00000000e+00]
 [-1.45963375e+02  3.23017130e+02  2.25650110e+04  3.32882324e+02
  -1.45963375e+02  3.23017130e+02]
 [-4.76364562e+00  4.27233266e+00  3.32882324e+02  6.52504692e+00
  -4.76364562e+00  4.27233266e+00]
 [ 1.23825044e+01  1.68159265e+00 -1.45963375e+02 -4.76364562e+00
   1.23825044e+01  1.68159265e+00]
 [ 1.68159265e+00  6.00000000e+00  3.23017130e+02  4.27233266e+00
   1.68159265e+00  6.00000000e+00]]
Determinant: 0.0
[[ 1.23825044e+01  1.68159265e+00 -1.45963375e+02 -4.7