In [34]:
import scipy as sp
import numpy as np
import sympy as smp

In [35]:
import math
def create_function(expression):
    t = smp.symbols('t')
    func = smp.lambdify(t, expression, 'numpy')
    return func



In [36]:

while True:
    try:
        rows =  int(input("ROWS: "))
        break
    except Exception:
        print("SHOULD BE INT ")
while True:
    try:        
        columns =int(input("COLUMNS: "))
        break
    except Exception:
        print("SHOULD BE INT ")  
inp = []
i = 0
while i < rows:
    
    data = input(f"Insert functions that depend on t or scalars as a row with length = {columns}: ").split()
    if len(data) != columns:
        print(f"ERROR: Row should have a length of {columns}.")
        continue

    try:
        tmp = lambda t, data=data: np.array([create_function(smp.sympify(expr))(t) for expr in data])
        inp.append(tmp)
        print(f"You've inserted a row {i + 1}")
        i += 1
    except smp.SympifyError:
        print("ERROR: Insert valid functions or scalars.")
        continue
            
A = lambda t: np.array([i(t) for i in inp])



ROWS: 2
COLUMNS: 2
Insert functions that depend on t or scalars as a row with length = 2: sin(t) 1-t**3
You've inserted a row 1
Insert functions that depend on t or scalars as a row with length = 2: t**2 cos(t)
You've inserted a row 2


In [37]:
while True:
    try:        
        data =input("B :  (len should = {})".format(rows)).split()
        if len(data) != rows:
            raise ValueError
        b = np.array([float(i) for i in data ])
        break
    except Exception:
        print("B :  (len should = {})".format(rows))  
b

B :  (len should = 2)5.322 5.067


array([5.322, 5.067])

In [38]:
v = 0
while True:
    try:        
        data =input("v :  (len should = {})".format(columns)).split()
        if len(data) != columns:
            raise ValueError
        v = lambda t, data=data: np.array([create_function(smp.sympify(expr))(t) for expr in data]) 
        break
    except Exception:
        print("v :  (len should = {})".format(columns))  
v(1)        

v :  (len should = 2)0  0


array([0, 0])

In [39]:
#A = lambda t:np.array([[t*50-1.23, np.sin(t)+2], [(t*2)**2 + np.pi, np.cos(t)], [np.exp(t), np.cos(t)**2]])
#b = np.array([1.4, -2.12, 3])
#v = lambda t: np.array([t*5-3, np.log(t)]) 

In [40]:
T = 1

In [41]:
A(0)[0]

array([0., 1.])

In [42]:
from scipy.integrate import quad_vec

P = quad_vec(lambda tau: A(tau) @ A(tau).T, 0, T )[0]

In [43]:

x_hat= lambda tau: A(tau).T @ np.linalg.pinv(P) @ b
x_hat(1)#1.45

array([ 4.49736149, -1.18789491])

In [44]:
Av = quad_vec(lambda tau: A(tau) @ v(tau).T, 0, T )[0]


In [45]:
Omega_xt =  lambda t : A(t).T @ np.linalg.pinv(P) @b + v(t) - A(t).T @ np.linalg.pinv(P) @ Av # 1.43

In [46]:
Omega_xt(1) 

array([ 4.49736149, -1.18789491])

In [47]:
eps_sq = b.T @ b - b.T @ P @ np.linalg.pinv(P) @ b
eps_sq

2.4158453015843406e-13

In [50]:
check1 = quad_vec(lambda tau: A(tau) @ Omega_xt(tau),0, 1)[0]
check1

array([5.322, 5.067])

In [51]:
check2 = quad_vec(lambda tau: A(tau) @ x_hat(tau),0, 1)[0]
check2

array([5.322, 5.067])

In [16]:
matrices_A_t = []
matrices_A_j = []
N = 5
length = np.array((A(1).T @ A(1))).shape[0]
def check(N):
    answ = np.zeros((length * (N ), length * (N )))
    # Compute matrices_A_t and matrices_A_j
    for i in range(N ):
        A_ti = A(T/(N-1) * i).T
        A_tj = A(T/(N-1) * i)
        matrices_A_t.append(np.array(A_ti))
        matrices_A_j.append(np.array(A_tj))
    for i in range(N ):
        for j in range(N):
            answ[i*length:(i+1)*length, j*length:(j+1)*length] = np.dot(matrices_A_t[i], matrices_A_j[j])
    determinant = np.linalg.det(answ)

    print("Determinant:", determinant)

    print(answ)
for i in range(2,N+1):
    check(i)

Determinant: 0.0
[[0.         0.         0.         0.        ]
 [0.         2.         1.84147098 0.54030231]
 [0.         1.84147098 1.70807342 0.54030231]
 [0.         0.54030231 0.54030231 0.29192658]]
Determinant: 0.0
[[0.         0.         0.         0.         0.         0.        ]
 [0.         2.         1.84147098 0.54030231 0.         2.        ]
 [0.         1.84147098 1.70807342 0.54030231 0.         1.84147098]
 [0.         0.54030231 0.54030231 0.29192658 0.         0.54030231]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         2.         1.84147098 0.54030231 0.         2.        ]]
Determinant: 0.0
[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         2.         1.84147098 0.54030231 0.         2.
  0.72942554 1.75258256]
 [0.         1.84147098 1.70807342 0.54030231 0.         1.84147098
  0.65342268 1.61386967]
 [0.         0.54030231 0.54030231 0.29192658 0.         0.54030231
  0.13507558 0

In [52]:
import sympy as sp




# Define the symbolic variable
t = sp.symbols('t')
tau = sp.symbols('tau')  # Define the symbolic variable for integration

# Function to create symbolic functions
def create_function(expression):
    return expression

while True:
    try:
        rows = int(input("ROWS: "))
        break
    except ValueError:
        print("SHOULD BE INT")

while True:
    try:
        columns = int(input("COLUMNS: "))
        break
    except ValueError:
        print("SHOULD BE INT")

inp = []
i = 0
while i < rows:
    data = input(f"Insert functions that depend on t or scalars as a row with length = {columns}: ").split()
    if len(data) != columns:
        print(f"ERROR: Row should have a length of {columns}.")
        continue

    try:
        tmp = [create_function(sp.sympify(expr)) for expr in data]
        inp.append(tmp)
        print(f"You've inserted a row {i + 1}")
        i += 1
    except sp.SympifyError:
        print("ERROR: Insert valid functions or scalars.")
        continue

# Define a symbolic matrix A
A = sp.Matrix(inp)

while True:
    try:
        data = input("B :  (len should = {})".format(rows)).split()
        if len(data) != rows:
            raise ValueError
        b = sp.Matrix([float(i) for i in data]).reshape(rows, 1)  # Make b a column vector
        break
    except ValueError:
        print("B :  (len should = {})".format(rows))

while True:
    try:
        data = input("v :  (len should = {})".format(columns)).split()
        if len(data) != columns:
            raise ValueError
        v = sp.Matrix([create_function(sp.sympify(expr)) for expr in data]).reshape(columns, 1)  # Make v a column vector
        break
    except ValueError:
        print("v :  (len should = {})".format(columns))

        print("v :  (len should = {})".format(columns))



P = sp.Matrix(P)

Omega_xt = A.T @ P.inv() @ b + v - (A.T @ P.inv() @ Av).reshape(2,1)   # 1.43



ROWS: 2
COLUMNS: 2
Insert functions that depend on t or scalars as a row with length = 2: sin(t) 1-t**3
You've inserted a row 1
Insert functions that depend on t or scalars as a row with length = 2: t**2 cos(t)
You've inserted a row 2
B :  (len should = 2)5.322 5.067
v :  (len should = 2)0 0


In [53]:
Omega_xt.as_immutable

<bound method DenseMatrix.as_immutable of Matrix([
[                   -2.19857456155798*t**2 + 7.95741763765771*sin(t)],
[-7.95741763765771*t**3 - 2.19857456155798*cos(t) + 7.95741763765771]])>

In [58]:
Omega_xt.subs(t,  1)

Matrix([
[-2.19857456155798 + 7.95741763765771*sin(1)],
[                   -2.19857456155798*cos(1)]])

In [60]:
7.95 * np.sin(1) -2.1985

4.491194329222777

In [61]:
-2.1985 * np.cos(1)

-1.1878546194511053